### PR TITLE
Update info.json

### PR DESCRIPTION
**Pull request by dnmTX**
adding squidblacklist.org_malware for comparison

### CODE REVIEW

**Comment by funilrys** [comment]
Output from CI:

```
Ultimate Hosts Blacklist: 1,960,683
    IP: 256,964 (13.11%)
    Domains: 1,703,719 (86.89%)
The list: 69,334
    IP: 0 (0.00%)
    Domains: 69,334 (100.00%)
Not present: 58,496 (84.37%)
    IP: 0 (0.00%)
    Domains: 58,496 (84.37%)
```

**Comment by dnmTX** [comment]
58,000+ unique domains...i'd say not bad at all

**Comment by dnmTX** [comment]
@funilrys  so what's the verdict on this one? Are we dropping it or you'll merge it? Just curious cause you didn't post any opinion so i'm left wondering about it.

**Comment by funilrys** [comment]
@dnmTX I just wanted to retest it. But for me it's good.

**Pull request closed without merging**
