### PR TITLE
Update info.json

### PR DESCRIPTION
**Pull request by dnmTX**
adding squdblacklist.org_adservers for comparison

### CODE REVIEW

**Comment by funilrys** [comment]
Output from CI:

```
Ultimate Hosts Blacklist: 1,960,683
    IP: 256,964 (13.11%)
    Domains: 1,703,719 (86.89%)
The list: 4,383
    IP: 0 (0.00%)
    Domains: 4,383 (100.00%)
Not present: 1,482 (33.81%)
    IP: 0 (0.00%)
    Domains: 1,482 (33.81%)
```

**Comment by dnmTX** [comment]
just 1,400+....i vote NO on this one 👎

**Comment by spirillen** [comment]
I would say 1482 is a better submission than 0, that's maybe not _that_ many but still..

My 2 cents

**Comment by dnmTX** [comment]
> I would say 1482 is a better submission than 0, that's maybe not that many but still..

My 2 cents

GO AWAY !!!!!

**Pull request closed without merging**
