### PR TITLE
Test for the (possible) introduction of #36 into our infrastructure

### PR DESCRIPTION
**Pull request by funilrys**

### CODE REVIEW

**Comment by funilrys** [comment]
Test result:

```
Ultimate Hosts Blacklist: 2,585,483
    IP: 212,423 (8.22%)
    Domains: 2,373,060 (91.78%)
The list: 15,621
    IP: 0 (0.00%)
    Domains: 15,621 (100.00%)
Not present: 5,313 (34.01%)
    IP: 0 (0.00%)
    Domains: 5,313 (34.01%)
```

**Comment by dnmTX** [comment]
@funilrys ,Steve @StevenBlack already merged this into his lists so mines as well. 
No arguments from my side,there were lots of likes when it was introduced there so i guess it will be beneficial for anyone using the **Ultimate-Hosts-Blacklist** in Vietnam. 👍

**Comment by StevenBlack** [comment]
Nissar @funilrys and Dan @dnmTX, it's dawning on me that a great source of future quality is region-specific and nation-specific curation.  Poland and Vietnam are just the beginning.  I'm hoping for Russia, China, and India very soon, for example.

**Comment by dnmTX** [comment]
@StevenBlack 

> I'm hoping for Russia, China, and India very soon, for example.

Our friend @anudeepND is from India and his [LISTS](https://raw.githubusercontent.com/anudeepND/blacklist/master/adservers.txt) contain many advertising domains from there(probably half of the lists). 
Just passing some info 😄

**Comment by bigdargon** [comment]
@StevenBlack I really like your idea! Each person creates a source repo to update the list of advertising domains in each country. Each person will be responsible for managing that source. That's why hostsVN is created, there is always a list of only advertisers in Vietnam that are updated separately and a full list of advertising domains that are frequently accessed in Vietnam.
@dnmTX Thanks you!

**Comment by funilrys** [comment]
https://github.com/Ultimate-Hosts-Blacklist/hostsVN

**Pull request closed without merging**
